import { createVuetify } from 'vuetify';
import { mdi } from 'vuetify/iconsets/mdi-svg';
import 'vuetify/styles';
import {
    mdiAndroid,
    mdiBook,
    mdiBookOpenVariant,
    mdiChevronDown,
    mdiChevronLeft,
    mdiChevronRight,
    mdiChevronUp,
    mdiClose,
    mdiCloseCircle,
    mdiCodeJson,
    mdiContentSave,
    mdiDatabase,
    mdiDeleteForever,
    mdiDiscPlayer,
    mdiDocker,
    mdiDownload,
    mdiFile,
    mdiFileDocumentEdit,
    mdiFileExcel,
    mdiFileMove,
    mdiFileMusic,
    mdiFilePdfBox,
    mdiFilePowerpoint,
    mdiFileSearch,
    mdiFileVideo,
    mdiFileWord,
    mdiFolder,
    mdiFolderDownload,
    mdiFolderPlus,
    mdiFormatFont,
    mdiFormatItalic,
    mdiFormatTextWrappingOverflow,
    mdiFormatTextWrappingWrap,
    mdiGit,
    mdiHome,
    mdiImage,
    mdiImageSearch,
    mdiLanguageC,
    mdiLanguageCpp,
    mdiLanguageCsharp,
    mdiLanguageCss3,
    mdiLanguageGo,
    mdiLanguageHtml5,
    mdiLanguageJava,
    mdiLanguageJavascript,
    mdiLanguageKotlin,
    mdiLanguageLua,
    mdiLanguagePhp,
    mdiLanguagePython,
    mdiLanguageRust,
    mdiLanguageTypescript,
    mdiLinkBoxVariant,
    mdiLinkVariant,
    mdiLogin,
    mdiLogout,
    mdiMagnetOn,
    mdiMagnify,
    mdiMinidisc,
    mdiMusic,
    mdiPause,
    mdiPlay,
    mdiPowershell,
    mdiRefresh,
    mdiRepeat,
    mdiRepeatOff,
    mdiRepeatOnce,
    mdiScriptText,
    mdiShuffle,
    mdiShuffleDisabled,
    mdiSkipNext,
    mdiSkipPrevious,
    mdiSortAlphabeticalAscending,
    mdiSortAlphabeticalDescending,
    mdiSortClockAscending,
    mdiSortClockDescending,
    mdiSortNumericAscending,
    mdiSortNumericDescending,
    mdiSvg,
    mdiUpload,
    mdiVideo,
    mdiVuejs,
    mdiWindowRestore,
    mdiXml,
    mdiZipBox,
} from '@mdi/js';

export default createVuetify({
    icons: {
        defaultSet: 'mdi',
        aliases: {
            mdiAndroid,
            mdiBook,
            mdiBookOpenVariant,
            mdiChevronDown,
            mdiChevronLeft,
            mdiChevronRight,
            mdiChevronUp,
            mdiClose,
            mdiCloseCircle,
            mdiCodeJson,
            mdiContentSave,
            mdiDatabase,
            mdiDeleteForever,
            mdiDiscPlayer,
            mdiDocker,
            mdiDownload,
            mdiFile,
            mdiFileDocumentEdit,
            mdiFileExcel,
            mdiFileMove,
            mdiFileMusic,
            mdiFilePdfBox,
            mdiFilePowerpoint,
            mdiFileSearch,
            mdiFileVideo,
            mdiFileWord,
            mdiFolder,
            mdiFolderDownload,
            mdiFolderPlus,
            mdiFormatFont,
            mdiFormatItalic,
            mdiFormatTextWrappingOverflow,
            mdiFormatTextWrappingWrap,
            mdiGit,
            mdiHome,
            mdiImage,
            mdiImageSearch,
            mdiLanguageC,
            mdiLanguageCpp,
            mdiLanguageCsharp,
            mdiLanguageCss3,
            mdiLanguageGo,
            mdiLanguageHtml5,
            mdiLanguageJava,
            mdiLanguageJavascript,
            mdiLanguageKotlin,
            mdiLanguageLua,
            mdiLanguagePhp,
            mdiLanguagePython,
            mdiLanguageRust,
            mdiLanguageTypescript,
            mdiLinkBoxVariant,
            mdiLinkVariant,
            mdiLogin,
            mdiLogout,
            mdiMagnetOn,
            mdiMagnify,
            mdiMinidisc,
            mdiMusic,
            mdiPause,
            mdiPlay,
            mdiPowershell,
            mdiRefresh,
            mdiRepeat,
            mdiRepeatOff,
            mdiRepeatOnce,
            mdiScriptText,
            mdiShuffle,
            mdiShuffleDisabled,
            mdiSkipNext,
            mdiSkipPrevious,
            mdiSortAlphabeticalAscending,
            mdiSortAlphabeticalDescending,
            mdiSortClockAscending,
            mdiSortClockDescending,
            mdiSortNumericAscending,
            mdiSortNumericDescending,
            mdiSvg,
            mdiUpload,
            mdiVideo,
            mdiVuejs,
            mdiWindowRestore,
            mdiXml,
            mdiZipBox,
        },
        sets: {
            mdi,
        },
    },
    theme: {
        variations: {
            colors: [
                'primary',
                'secondary',
            ],
            lighten: 2,
            darken: 2,
        },
        themes: {
            light: {
                colors: {
                    primary: '#0288d1',
                    secondary: '#00b0ff',
                    ...(window.__DUFS_MATERIAL_CONFIG__?.theme?.light || {}),
                },
            },
            dark: {
                dark: true,
                colors: {
                    background: '#0f0f0f',
                    primary: '#0288d1',
                    secondary: '#00b0ff',
                    ...(window.__DUFS_MATERIAL_CONFIG__?.theme?.dark || {}),
                },
            },
        },
    },
});